name: Deploy redirects service

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout redirects-services
        uses: actions/checkout@v3
        with:
          repository: grrr-amsterdam/redirects-service
          ref: SERVICE_VERSION
          token: GITHUB_TOKEN

      - name: Checkout app
        uses: actions/checkout@v3
        with:
          path: app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: AWS_DEPLOY_ROLE
          aws-region: AWS_REGION

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: api/yarn.lock

      - name: Install dependencies
        working-directory: api
        run: yarn install

      - name: Deploy
        working-directory: api
        run: |
          cp ../app/redirects/serverless.yml .
          npx serverless deploy --config ../app/serverless.yml --stage STAGE --region AWS_REGION
