name: CI

on:
  push:

jobs:
  prettier:
    name: Code style
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - working-directory: "api"
            node: "18.x"

    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: ${{ matrix.working-directory }}/yarn.lock

      - run: yarn install

      - run: npx prettier --check .

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Validate Composer files
        run: composer validate --ansi

      - name: Install PHP dependencies
        run: |
          composer config --ansi -- http-basic.nova.laravel.com "laravel@grrr.nl" "${{ secrets.NOVA_PASSWORD }}"
          composer install --prefer-dist --no-interaction --ansi

      - name: Run static analysis
        run: composer static-analysis
